### ISSUE TITLE
How to run faster-rcnn from your code

### ISSUE THREAD

**Issue by Karthik-Suresh93** [zhpmatrix/VisDrone2018#2]
Hi, 

Can you give steps on how to run the pytorch faster rcnn code for visdrone from your repo? I am benchmarking faster-rcnn from different repos. Please let me know how to run this from your repo
Thank you very much

**Comment by Karthik-Suresh93** [comment]
I followed your instructions and am getting nan losses still. Did you face this issue too?

**Comment by zhpmatrix** [comment]
@Karthik-Suresh93 

I have sent a Gmail to you, please check it.

**Comment by liangxi627** [comment]
@zhpmatrix I'm new to pytorch, can you please send me an instruction to run your code? My email is 1507813621@qq.com
