### ISSUE TITLE
Patching Data Augmentation

### ISSUE THREAD

**Issue by Karthik-Suresh93** [zhpmatrix/VisDrone2018#3]
Hi @zhpmatrix,

You mention patching data augmentation that you used and obtained great results. Can you provide a link to a paper or code in which this has been implemented?

Thanks and Regards,
Karthik

**Comment by zhpmatrix** [comment]
Hello, @Karthik-Suresh93 

I did a survey about the ability of Faster R-CNN to detect small objects and found the data augmentation method named patching three weeks ago. And when I communicated this idea with @	ZhihongChen123, he said the implementation of this method is a little difficult for him, so I just helped him to implement this idea and He will check the idea with YOLO v3. This repo will not be updated.

The implementation of pathching is in my repo.

**Comment by Karthik-Suresh93** [comment]
Thanks @zhpmatrix . Do you have any paper in which this data augmentation method is explained? I searched but couldn't find any by this name

**Comment by zhpmatrix** [comment]
Sorry to confuse you with method as patching named by myself. Maybe this presentation will help you to understand motivation of this data augmentation(https://docs.google.com/presentation/d/1OTfGn6mLe1VWE8D0q6Tu_WwFTSoLGd4OF8WCYnOWcVo/edit#slide=id.p3), my implementation of patching is different from method with rotation as mentioned in presentation.

**Comment by Karthik-Suresh93** [comment]
Thank you very much!
